"""add_fk_constraints_report_branding

Revision ID: 071e0ba839ff
Revises: a8e6f76fe066
Create Date: 2026-06-03 23:57:43.672913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071e0ba839ff'
down_revision: Union[str, None] = 'a8e6f76fe066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_brand_assets_profile_id', table_name='brand_assets')
    op.drop_constraint('brand_assets_ibfk_1', 'brand_assets', type_='foreignkey')
    op.create_foreign_key(None, 'brand_assets', 'brand_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_brand_profiles_brand_ref', table_name='brand_profiles')
    op.drop_index('ix_brand_profiles_status', table_name='brand_profiles')
    op.drop_index('ix_brand_touchpoints_profile_id', table_name='brand_touchpoints')
    op.drop_constraint('brand_touchpoints_ibfk_1', 'brand_touchpoints', type_='foreignkey')
    op.create_foreign_key(None, 'brand_touchpoints', 'brand_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_payout_adjustments_payee_id', table_name='payout_adjustments')
    op.drop_index('ix_payout_payees_entity_id', table_name='payout_payees')
    op.drop_index('ix_payout_payees_run_id', table_name='payout_payees')
    op.drop_index('ix_payout_payees_status', table_name='payout_payees')
    op.drop_index('ix_payout_runs_run_ref', table_name='payout_runs')
    op.drop_index('ix_payout_runs_run_type', table_name='payout_runs')
    op.drop_index('ix_payout_runs_status', table_name='payout_runs')
    op.drop_index('ix_report_exports_status', table_name='report_exports')
    op.drop_index('ix_report_exports_template_id', table_name='report_exports')
    op.drop_constraint('report_exports_ibfk_1', 'report_exports', type_='foreignkey')
    op.create_foreign_key(None, 'report_exports', 'report_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_report_schedules_template_id', table_name='report_schedules')
    op.drop_constraint('report_schedules_ibfk_1', 'report_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'report_schedules', 'report_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_report_templates_is_standard', table_name='report_templates')
    op.drop_index('ix_report_templates_tag', table_name='report_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_report_templates_tag', 'report_templates', ['tag'], unique=False)
    op.create_index('ix_report_templates_is_standard', 'report_templates', ['is_standard'], unique=False)
    op.drop_constraint(None, 'report_schedules', type_='foreignkey')
    op.create_foreign_key('report_schedules_ibfk_1', 'report_schedules', 'report_templates', ['template_id'], ['id'])
    op.create_index('ix_report_schedules_template_id', 'report_schedules', ['template_id'], unique=False)
    op.drop_constraint(None, 'report_exports', type_='foreignkey')
    op.create_foreign_key('report_exports_ibfk_1', 'report_exports', 'report_templates', ['template_id'], ['id'])
    op.create_index('ix_report_exports_template_id', 'report_exports', ['template_id'], unique=False)
    op.create_index('ix_report_exports_status', 'report_exports', ['status'], unique=False)
    op.create_index('ix_payout_runs_status', 'payout_runs', ['status'], unique=False)
    op.create_index('ix_payout_runs_run_type', 'payout_runs', ['run_type'], unique=False)
    op.create_index('ix_payout_runs_run_ref', 'payout_runs', ['run_ref'], unique=False)
    op.create_index('ix_payout_payees_status', 'payout_payees', ['status'], unique=False)
    op.create_index('ix_payout_payees_run_id', 'payout_payees', ['run_id'], unique=False)
    op.create_index('ix_payout_payees_entity_id', 'payout_payees', ['entity_id'], unique=False)
    op.create_index('ix_payout_adjustments_payee_id', 'payout_adjustments', ['payee_id'], unique=False)
    op.drop_constraint(None, 'brand_touchpoints', type_='foreignkey')
    op.create_foreign_key('brand_touchpoints_ibfk_1', 'brand_touchpoints', 'brand_profiles', ['profile_id'], ['id'])
    op.create_index('ix_brand_touchpoints_profile_id', 'brand_touchpoints', ['profile_id'], unique=False)
    op.create_index('ix_brand_profiles_status', 'brand_profiles', ['status'], unique=False)
    op.create_index('ix_brand_profiles_brand_ref', 'brand_profiles', ['brand_ref'], unique=False)
    op.drop_constraint(None, 'brand_assets', type_='foreignkey')
    op.create_foreign_key('brand_assets_ibfk_1', 'brand_assets', 'brand_profiles', ['profile_id'], ['id'])
    op.create_index('ix_brand_assets_profile_id', 'brand_assets', ['profile_id'], unique=False)
    # ### end Alembic commands ###
