"""add_booking_type_to_tickets

Revision ID: 0b72e45cdc5f
Revises: b4c5d6e7f8a9
Create Date: 2026-06-10 23:35:03.588805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b72e45cdc5f'
down_revision: Union[str, None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operator_roles_operator_id', table_name='operator_roles')
    op.drop_table('operator_roles')
    op.drop_index('ix_operator_role_permissions_operator_role_id', table_name='operator_role_permissions')
    op.drop_table('operator_role_permissions')
    op.drop_index('ix_brand_assets_profile_id', table_name='brand_assets')
    op.drop_constraint('brand_assets_ibfk_1', 'brand_assets', type_='foreignkey')
    op.create_foreign_key(None, 'brand_assets', 'brand_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_brand_profiles_brand_ref', table_name='brand_profiles')
    op.drop_index('ix_brand_profiles_status', table_name='brand_profiles')
    op.drop_index('ix_brand_touchpoints_profile_id', table_name='brand_touchpoints')
    op.drop_constraint('brand_touchpoints_ibfk_1', 'brand_touchpoints', type_='foreignkey')
    op.create_foreign_key(None, 'brand_touchpoints', 'brand_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notification_logs_template_id'), 'notification_logs', ['template_id'], unique=False)
    op.drop_index('template_code', table_name='notification_templates')
    op.create_index(op.f('ix_notification_templates_template_code'), 'notification_templates', ['template_code'], unique=True)
    op.drop_index('ix_payout_adjustments_payee_id', table_name='payout_adjustments')
    op.drop_index('ix_payout_payees_entity_id', table_name='payout_payees')
    op.drop_index('ix_payout_payees_run_id', table_name='payout_payees')
    op.drop_index('ix_payout_payees_status', table_name='payout_payees')
    op.drop_index('ix_payout_runs_run_ref', table_name='payout_runs')
    op.drop_index('ix_payout_runs_run_type', table_name='payout_runs')
    op.drop_index('ix_payout_runs_status', table_name='payout_runs')
    op.drop_index('ix_report_exports_status', table_name='report_exports')
    op.drop_index('ix_report_exports_template_id', table_name='report_exports')
    op.drop_constraint('report_exports_ibfk_1', 'report_exports', type_='foreignkey')
    op.create_foreign_key(None, 'report_exports', 'report_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_report_schedules_template_id', table_name='report_schedules')
    op.drop_constraint('report_schedules_ibfk_1', 'report_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'report_schedules', 'report_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_report_templates_is_standard', table_name='report_templates')
    op.drop_index('ix_report_templates_tag', table_name='report_templates')
    op.add_column('tickets', sa.Column('linked_booking_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'linked_booking_type')
    op.create_index('ix_report_templates_tag', 'report_templates', ['tag'], unique=False)
    op.create_index('ix_report_templates_is_standard', 'report_templates', ['is_standard'], unique=False)
    op.drop_constraint(None, 'report_schedules', type_='foreignkey')
    op.create_foreign_key('report_schedules_ibfk_1', 'report_schedules', 'report_templates', ['template_id'], ['id'])
    op.create_index('ix_report_schedules_template_id', 'report_schedules', ['template_id'], unique=False)
    op.drop_constraint(None, 'report_exports', type_='foreignkey')
    op.create_foreign_key('report_exports_ibfk_1', 'report_exports', 'report_templates', ['template_id'], ['id'])
    op.create_index('ix_report_exports_template_id', 'report_exports', ['template_id'], unique=False)
    op.create_index('ix_report_exports_status', 'report_exports', ['status'], unique=False)
    op.create_index('ix_payout_runs_status', 'payout_runs', ['status'], unique=False)
    op.create_index('ix_payout_runs_run_type', 'payout_runs', ['run_type'], unique=False)
    op.create_index('ix_payout_runs_run_ref', 'payout_runs', ['run_ref'], unique=False)
    op.create_index('ix_payout_payees_status', 'payout_payees', ['status'], unique=False)
    op.create_index('ix_payout_payees_run_id', 'payout_payees', ['run_id'], unique=False)
    op.create_index('ix_payout_payees_entity_id', 'payout_payees', ['entity_id'], unique=False)
    op.create_index('ix_payout_adjustments_payee_id', 'payout_adjustments', ['payee_id'], unique=False)
    op.drop_index(op.f('ix_notification_templates_template_code'), table_name='notification_templates')
    op.create_index('template_code', 'notification_templates', ['template_code'], unique=True)
    op.drop_index(op.f('ix_notification_logs_template_id'), table_name='notification_logs')
    op.drop_constraint(None, 'brand_touchpoints', type_='foreignkey')
    op.create_foreign_key('brand_touchpoints_ibfk_1', 'brand_touchpoints', 'brand_profiles', ['profile_id'], ['id'])
    op.create_index('ix_brand_touchpoints_profile_id', 'brand_touchpoints', ['profile_id'], unique=False)
    op.create_index('ix_brand_profiles_status', 'brand_profiles', ['status'], unique=False)
    op.create_index('ix_brand_profiles_brand_ref', 'brand_profiles', ['brand_ref'], unique=False)
    op.drop_constraint(None, 'brand_assets', type_='foreignkey')
    op.create_foreign_key('brand_assets_ibfk_1', 'brand_assets', 'brand_profiles', ['profile_id'], ['id'])
    op.create_index('ix_brand_assets_profile_id', 'brand_assets', ['profile_id'], unique=False)
    op.create_table('operator_role_permissions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('operator_role_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('permission', mysql.VARCHAR(length=120), nullable=False),
    sa.ForeignKeyConstraint(['operator_role_id'], ['operator_roles.id'], name='operator_role_permissions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_operator_role_permissions_operator_role_id', 'operator_role_permissions', ['operator_role_id'], unique=False)
    op.create_table('operator_roles',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('operator_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('display_name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('is_system', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name='operator_roles_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_operator_roles_operator_id', 'operator_roles', ['operator_id'], unique=False)
    # ### end Alembic commands ###
