"""add_operators_aircraft_pilots

Revision ID: 0fa38c92e3ff
Revises: 477f8af4c50d
Create Date: 2026-05-30 22:58:55.123312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa38c92e3ff'
down_revision: Union[str, None] = '477f8af4c50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_registration_no', sa.String(length=100), nullable=True),
    sa.Column('hq_city', sa.String(length=100), nullable=True),
    sa.Column('cert_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('commission_pct', sa.Float(), nullable=True),
    sa.Column('payout_account_ref', sa.String(length=200), nullable=True),
    sa.Column('site_visit_status', sa.String(length=20), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('cert_expiry', sa.Date(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_name'), 'operators', ['name'], unique=False)
    op.create_index(op.f('ix_operators_status'), 'operators', ['status'], unique=False)
    op.create_table('aircraft',
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('aircraft_type_id', sa.String(length=36), nullable=True),
    sa.Column('registration_mark', sa.String(length=50), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('mtow_kg', sa.Integer(), nullable=True),
    sa.Column('range_nm', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('airworthiness_status', sa.String(length=20), nullable=False),
    sa.Column('airworthiness_expiry', sa.Date(), nullable=True),
    sa.Column('airworthiness_doc_url', sa.String(length=500), nullable=True),
    sa.Column('maintenance_windows', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_operator_id'), 'aircraft', ['operator_id'], unique=False)
    op.create_index(op.f('ix_aircraft_registration_mark'), 'aircraft', ['registration_mark'], unique=True)
    op.create_index(op.f('ix_aircraft_status'), 'aircraft', ['status'], unique=False)
    op.create_table('operator_documents',
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_documents_operator_id'), 'operator_documents', ['operator_id'], unique=False)
    op.create_table('pilots',
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('license_no', sa.String(length=100), nullable=True),
    sa.Column('license_type', sa.String(length=20), nullable=True),
    sa.Column('type_ratings', sa.JSON(), nullable=True),
    sa.Column('medical_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilots_name'), 'pilots', ['name'], unique=False)
    op.create_index(op.f('ix_pilots_operator_id'), 'pilots', ['operator_id'], unique=False)
    op.create_index(op.f('ix_pilots_status'), 'pilots', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pilots_status'), table_name='pilots')
    op.drop_index(op.f('ix_pilots_operator_id'), table_name='pilots')
    op.drop_index(op.f('ix_pilots_name'), table_name='pilots')
    op.drop_table('pilots')
    op.drop_index(op.f('ix_operator_documents_operator_id'), table_name='operator_documents')
    op.drop_table('operator_documents')
    op.drop_index(op.f('ix_aircraft_status'), table_name='aircraft')
    op.drop_index(op.f('ix_aircraft_registration_mark'), table_name='aircraft')
    op.drop_index(op.f('ix_aircraft_operator_id'), table_name='aircraft')
    op.drop_table('aircraft')
    op.drop_index(op.f('ix_operators_status'), table_name='operators')
    op.drop_index(op.f('ix_operators_name'), table_name='operators')
    op.drop_table('operators')
    # ### end Alembic commands ###
