"""add_vehicle_fleet_module

Revision ID: 1547377ac5c9
Revises: d47cf9e3acce
Create Date: 2026-05-29 23:30:25.124665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1547377ac5c9'
down_revision: Union[str, None] = 'd47cf9e3acce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('flag_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('plate_no', sa.String(length=40), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('vehicle_class_id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_vendor_id', sa.String(length=36), nullable=True),
    sa.Column('linked_driver_id', sa.String(length=36), nullable=True),
    sa.Column('linked_since', sa.DateTime(), nullable=True),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('doc_status', sa.String(length=20), nullable=False),
    sa.Column('flag_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['owner_vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['vehicle_class_id'], ['vehicle_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_linked_driver_id'), 'vehicles', ['linked_driver_id'], unique=False)
    op.create_index(op.f('ix_vehicles_owner_vendor_id'), 'vehicles', ['owner_vendor_id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_no'), 'vehicles', ['plate_no'], unique=True)
    op.create_index(op.f('ix_vehicles_vehicle_class_id'), 'vehicles', ['vehicle_class_id'], unique=False)
    op.create_table('vehicle_documents',
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('doc_number', sa.String(length=100), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_documents_vehicle_id'), 'vehicle_documents', ['vehicle_id'], unique=False)
    op.create_table('vehicle_maintenances',
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_label', sa.String(length=200), nullable=False),
    sa.Column('milestone_km', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('service_center', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_maintenances_vehicle_id'), 'vehicle_maintenances', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_maintenances_vehicle_id'), table_name='vehicle_maintenances')
    op.drop_table('vehicle_maintenances')
    op.drop_index(op.f('ix_vehicle_documents_vehicle_id'), table_name='vehicle_documents')
    op.drop_table('vehicle_documents')
    op.drop_index(op.f('ix_vehicles_vehicle_class_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate_no'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_owner_vendor_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_linked_driver_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('vendors')
    # ### end Alembic commands ###
