"""add_module_05_air_bookings

Revision ID: 43f9a55765ff
Revises: b07cdf4be1af
Create Date: 2026-05-31 13:31:09.107602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base

# revision identifiers, used by Alembic.
revision: str = '43f9a55765ff'
down_revision: Union[str, None] = 'b07cdf4be1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_bookings',
    sa.Column('booking_ref', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('aircraft_id', sa.String(length=36), nullable=True),
    sa.Column('service_subtype', sa.String(length=40), nullable=False),
    sa.Column('service_label', sa.String(length=60), nullable=False),
    sa.Column('route_from', sa.String(length=200), nullable=False),
    sa.Column('route_to', sa.String(length=200), nullable=False),
    sa.Column('pax_count', sa.Integer(), nullable=False),
    sa.Column('etd', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('eta', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fare_estimate_minor', sa.Integer(), nullable=False),
    sa.Column('fare_final_minor', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_reason', sa.Text(), nullable=True),
    sa.Column('reschedule_ref', sa.String(length=20), nullable=True),
    sa.Column('manifest_locked', sa.Boolean(), nullable=False),
    sa.Column('manifest_locked_at', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('distance_nm', sa.Float(), nullable=True),
    sa.Column('flight_time_min', sa.Integer(), nullable=True),
    sa.Column('fuel_weight_kg', sa.Float(), nullable=True),
    sa.Column('operator_otp_pct', sa.Float(), nullable=True),
    sa.Column('operator_fleet_count', sa.Integer(), nullable=True),
    sa.Column('aircraft_model', sa.String(length=100), nullable=True),
    sa.Column('aircraft_seats', sa.Integer(), nullable=True),
    sa.Column('aircraft_mtow_kg', sa.Float(), nullable=True),
    sa.Column('aircraft_airworthy_until', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('aircraft_registration', sa.String(length=20), nullable=True),
    sa.Column('pilot_name', sa.String(length=100), nullable=True),
    sa.Column('pilot_license', sa.String(length=100), nullable=True),
    sa.Column('copilot_name', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_bookings_aircraft_id'), 'air_bookings', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_air_bookings_booking_ref'), 'air_bookings', ['booking_ref'], unique=True)
    op.create_index(op.f('ix_air_bookings_customer_id'), 'air_bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_air_bookings_operator_id'), 'air_bookings', ['operator_id'], unique=False)
    op.create_index(op.f('ix_air_bookings_status'), 'air_bookings', ['status'], unique=False)
    op.create_table('air_booking_notes',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['air_bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_booking_notes_booking_id'), 'air_booking_notes', ['booking_id'], unique=False)
    op.create_table('air_booking_timeline',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['air_bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_booking_timeline_booking_id'), 'air_booking_timeline', ['booking_id'], unique=False)
    op.create_table('charter_quotes',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('operator_name', sa.String(length=200), nullable=True),
    sa.Column('aircraft_registration', sa.String(length=20), nullable=True),
    sa.Column('aircraft_model', sa.String(length=100), nullable=True),
    sa.Column('pax_capacity', sa.Integer(), nullable=True),
    sa.Column('range_nm', sa.Integer(), nullable=True),
    sa.Column('depart_icao', sa.String(length=10), nullable=True),
    sa.Column('arrive_icao', sa.String(length=10), nullable=True),
    sa.Column('etd', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('eta', app.models.base.UTCDateTime(), nullable=True),
    sa.Column('base_fare_minor', sa.Integer(), nullable=False),
    sa.Column('positioning_minor', sa.Integer(), nullable=False),
    sa.Column('night_halt_minor', sa.Integer(), nullable=False),
    sa.Column('catering_minor', sa.Integer(), nullable=False),
    sa.Column('fuel_surcharge_minor', sa.Integer(), nullable=False),
    sa.Column('taxes_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('otp_30d_pct', sa.Float(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['air_bookings.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charter_quotes_booking_id'), 'charter_quotes', ['booking_id'], unique=False)
    op.create_index(op.f('ix_charter_quotes_operator_id'), 'charter_quotes', ['operator_id'], unique=False)
    op.create_table('manifest_passengers',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('id_number', sa.String(length=200), nullable=True),
    sa.Column('body_weight_kg', sa.Float(), nullable=False),
    sa.Column('baggage_weight_kg', sa.Float(), nullable=False),
    sa.Column('special_notes', sa.String(length=500), nullable=True),
    sa.Column('is_minor', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['air_bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manifest_passengers_booking_id'), 'manifest_passengers', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manifest_passengers_booking_id'), table_name='manifest_passengers')
    op.drop_table('manifest_passengers')
    op.drop_index(op.f('ix_charter_quotes_operator_id'), table_name='charter_quotes')
    op.drop_index(op.f('ix_charter_quotes_booking_id'), table_name='charter_quotes')
    op.drop_table('charter_quotes')
    op.drop_index(op.f('ix_air_booking_timeline_booking_id'), table_name='air_booking_timeline')
    op.drop_table('air_booking_timeline')
    op.drop_index(op.f('ix_air_booking_notes_booking_id'), table_name='air_booking_notes')
    op.drop_table('air_booking_notes')
    op.drop_index(op.f('ix_air_bookings_status'), table_name='air_bookings')
    op.drop_index(op.f('ix_air_bookings_operator_id'), table_name='air_bookings')
    op.drop_index(op.f('ix_air_bookings_customer_id'), table_name='air_bookings')
    op.drop_index(op.f('ix_air_bookings_booking_ref'), table_name='air_bookings')
    op.drop_index(op.f('ix_air_bookings_aircraft_id'), table_name='air_bookings')
    op.drop_table('air_bookings')
    # ### end Alembic commands ###
