"""add_data_privacy_to_platform_settings

Revision ID: 477f8af4c50d
Revises: bbd8d85c6dbd
Create Date: 2026-05-30 22:30:55.430538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477f8af4c50d'
down_revision: Union[str, None] = 'bbd8d85c6dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('data_retention_trip_days', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('data_retention_pii_days', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('data_retention_financial_years', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('data_retention_audit_years', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('privacy_export_sla_hours', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('privacy_deletion_sla_days', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('privacy_auto_anonymize', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('consent_marketing_opt_in', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('consent_analytics_tracking', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('consent_cookie_banner', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('data_share_authorities', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'data_share_authorities')
    op.drop_column('platform_settings', 'consent_cookie_banner')
    op.drop_column('platform_settings', 'consent_analytics_tracking')
    op.drop_column('platform_settings', 'consent_marketing_opt_in')
    op.drop_column('platform_settings', 'privacy_auto_anonymize')
    op.drop_column('platform_settings', 'privacy_deletion_sla_days')
    op.drop_column('platform_settings', 'privacy_export_sla_hours')
    op.drop_column('platform_settings', 'data_retention_audit_years')
    op.drop_column('platform_settings', 'data_retention_financial_years')
    op.drop_column('platform_settings', 'data_retention_pii_days')
    op.drop_column('platform_settings', 'data_retention_trip_days')
    # ### end Alembic commands ###
