"""add_module_13_pricing_tables

Revision ID: 4ff42c5b0ed7
Revises: 1547377ac5c9
Create Date: 2026-05-30 01:39:51.229893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff42c5b0ed7'
down_revision: Union[str, None] = '1547377ac5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_fare_rules',
    sa.Column('rule_code', sa.String(length=40), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('per_seat_base', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_pax', sa.Integer(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('baggage_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('excess_baggage_cap', sa.Integer(), nullable=False),
    sa.Column('positioning_charge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('night_halt_charge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fuel_surcharge_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_gst_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_fare_rules_rule_code'), 'air_fare_rules', ['rule_code'], unique=True)
    op.create_table('tax_rules',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('inclusive', sa.Boolean(), nullable=False),
    sa.Column('in_use', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_rules',
    sa.Column('rule_code', sa.String(length=30), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_class_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_km', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('per_min', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('min_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('free_km', sa.Integer(), nullable=False),
    sa.Column('free_min', sa.Integer(), nullable=False),
    sa.Column('waiting_per_min', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cancel_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('surge_cap', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('modifiers', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_class_id'], ['vehicle_classes.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['service_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_rule_code'), 'pricing_rules', ['rule_code'], unique=True)
    op.create_index(op.f('ix_pricing_rules_vehicle_class_id'), 'pricing_rules', ['vehicle_class_id'], unique=False)
    op.create_index(op.f('ix_pricing_rules_zone_id'), 'pricing_rules', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_rules_zone_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_vehicle_class_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_rule_code'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_table('tax_rules')
    op.drop_index(op.f('ix_air_fare_rules_rule_code'), table_name='air_fare_rules')
    op.drop_table('air_fare_rules')
    # ### end Alembic commands ###
