"""add_zone_operational_status_drop_region_status

Revision ID: 92365e6f29ee
Revises: 9c8e0304238b
Create Date: 2026-05-30 16:35:43.407445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92365e6f29ee'
down_revision: Union[str, None] = '9c8e0304238b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_status')
    op.add_column('service_zones', sa.Column('operational_status', sa.String(length=20), nullable=False, server_default='operational'))
    op.add_column('service_zones', sa.Column('status_note', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_zones', 'status_note')
    op.drop_column('service_zones', 'operational_status')
    op.create_table('region_status',
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('service_type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('note', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
