"""add_module_06_dispatch

Revision ID: 9312b379c6e6
Revises: 523b842a6a2a
Create Date: 2026-05-31 19:15:47.697316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9312b379c6e6'
down_revision: Union[str, None] = '523b842a6a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surge_overrides',
    sa.Column('zone_id', sa.String(length=20), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('applies_to', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bookings_affected', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surge_overrides_zone_id'), 'surge_overrides', ['zone_id'], unique=False)
    op.create_table('dispatch_exceptions',
    sa.Column('exception_ref', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=20), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_class', sa.String(length=40), nullable=True),
    sa.Column('dispatch_attempts', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('recommended_action', sa.String(length=200), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('resolved_by_driver_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['road_bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_exceptions_booking_id'), 'dispatch_exceptions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_dispatch_exceptions_exception_ref'), 'dispatch_exceptions', ['exception_ref'], unique=True)
    op.drop_index('booking_id', table_name='disputes')
    op.add_column('drivers', sa.Column('current_lat', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('current_lng', sa.Float(), nullable=True))
    op.add_column('road_bookings', sa.Column('dispatch_attempts', sa.Integer(), nullable=False))
    op.add_column('road_bookings', sa.Column('current_radius_km', sa.Float(), nullable=False))
    op.add_column('road_bookings', sa.Column('zone_id', sa.String(length=20), nullable=True))
    op.add_column('road_bookings', sa.Column('zone_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('road_bookings', 'zone_name')
    op.drop_column('road_bookings', 'zone_id')
    op.drop_column('road_bookings', 'current_radius_km')
    op.drop_column('road_bookings', 'dispatch_attempts')
    op.drop_column('drivers', 'current_lng')
    op.drop_column('drivers', 'current_lat')
    op.create_index('booking_id', 'disputes', ['booking_id'], unique=True)
    op.drop_index(op.f('ix_dispatch_exceptions_exception_ref'), table_name='dispatch_exceptions')
    op.drop_index(op.f('ix_dispatch_exceptions_booking_id'), table_name='dispatch_exceptions')
    op.drop_table('dispatch_exceptions')
    op.drop_index(op.f('ix_surge_overrides_zone_id'), table_name='surge_overrides')
    op.drop_table('surge_overrides')
    # ### end Alembic commands ###
