"""add_safety_sos_to_platform_settings

Revision ID: 94fefaf90323
Revises: db6e07eb52b7
Create Date: 2026-05-30 18:34:34.536859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fefaf90323'
down_revision: Union[str, None] = 'db6e07eb52b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('sos_enabled', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('sos_contact_number', sa.String(length=20), nullable=True))
    op.add_column('platform_settings', sa.Column('sos_share_location', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('sos_alert_admin', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('driver_grace_period_enabled', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('driver_grace_period_days', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('operator_site_visit_required', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('driver_min_rating', sa.Float(), nullable=True))
    op.add_column('platform_settings', sa.Column('driver_max_cancellation_rate_pct', sa.Float(), nullable=True))
    op.add_column('platform_settings', sa.Column('driver_min_acceptance_rate_pct', sa.Float(), nullable=True))
    op.add_column('platform_settings', sa.Column('driver_threshold_window_days', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('sla_dispatch_alert_min', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('sla_pickup_alert_min', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('sla_trip_overrun_alert_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'sla_trip_overrun_alert_min')
    op.drop_column('platform_settings', 'sla_pickup_alert_min')
    op.drop_column('platform_settings', 'sla_dispatch_alert_min')
    op.drop_column('platform_settings', 'driver_threshold_window_days')
    op.drop_column('platform_settings', 'driver_min_acceptance_rate_pct')
    op.drop_column('platform_settings', 'driver_max_cancellation_rate_pct')
    op.drop_column('platform_settings', 'driver_min_rating')
    op.drop_column('platform_settings', 'operator_site_visit_required')
    op.drop_column('platform_settings', 'driver_grace_period_days')
    op.drop_column('platform_settings', 'driver_grace_period_enabled')
    op.drop_column('platform_settings', 'sos_alert_admin')
    op.drop_column('platform_settings', 'sos_share_location')
    op.drop_column('platform_settings', 'sos_contact_number')
    op.drop_column('platform_settings', 'sos_enabled')
    # ### end Alembic commands ###
