"""add_module_11_customers

Revision ID: 9a6f498e9ac3
Revises: 008
Create Date: 2026-05-28 20:54:53.255378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a6f498e9ac3'
down_revision: Union[str, None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('seq_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('computed_segment', sa.String(length=20), nullable=False),
    sa.Column('segment_override', sa.String(length=20), nullable=True),
    sa.Column('wallet_balance_minor', sa.Integer(), nullable=False),
    sa.Column('trips_count', sa.Integer(), nullable=False),
    sa.Column('ltv_minor', sa.Integer(), nullable=False),
    sa.Column('avg_fare_minor', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('cancellation_rate', sa.Float(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq_id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_table('wallet_transactions',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('audit_note', sa.String(length=500), nullable=True),
    sa.Column('notify_push', sa.Boolean(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_customer_id'), 'wallet_transactions', ['customer_id'], unique=False)
    op.drop_index('token_hash', table_name='admin_invite_tokens')
    op.drop_index('ix_admin_invite_tokens_token_hash', table_name='admin_invite_tokens')
    op.create_index(op.f('ix_admin_invite_tokens_token_hash'), 'admin_invite_tokens', ['token_hash'], unique=True)
    op.alter_column('admin_sessions', 'refresh_token_hash',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('admin_sessions', 'device_os',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('refresh_token_hash', table_name='admin_sessions')
    op.drop_constraint('admin_sessions_ibfk_1', 'admin_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'admin_sessions', 'admin_users', ['admin_user_id'], ['id'])
    op.drop_index('email', table_name='admin_users')
    op.drop_index('ix_admin_users_email', table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.drop_index('code', table_name='air_routes')
    op.drop_index('ix_air_routes_code', table_name='air_routes')
    op.create_index(op.f('ix_air_routes_code'), 'air_routes', ['code'], unique=True)
    op.drop_index('code', table_name='aircraft_types')
    op.drop_index('ix_aircraft_types_code', table_name='aircraft_types')
    op.create_index(op.f('ix_aircraft_types_code'), 'aircraft_types', ['code'], unique=True)
    op.alter_column('password_reset_tokens', 'token_hash',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('token_hash', table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_admin_user_id'), 'password_reset_tokens', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.drop_constraint('password_reset_tokens_ibfk_1', 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'admin_users', ['admin_user_id'], ['id'])
    op.drop_index('code', table_name='service_zones')
    op.drop_index('ix_service_zones_code', table_name='service_zones')
    op.create_index(op.f('ix_service_zones_code'), 'service_zones', ['code'], unique=True)
    op.alter_column('sign_in_history', 'result',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('sign_in_history', 'user_agent',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint('sign_in_history_ibfk_1', 'sign_in_history', type_='foreignkey')
    op.create_foreign_key(None, 'sign_in_history', 'admin_users', ['admin_user_id'], ['id'])
    op.drop_index('code', table_name='vehicle_classes')
    op.drop_index('ix_vehicle_classes_code', table_name='vehicle_classes')
    op.create_index(op.f('ix_vehicle_classes_code'), 'vehicle_classes', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_classes_code'), table_name='vehicle_classes')
    op.create_index('ix_vehicle_classes_code', 'vehicle_classes', ['code'], unique=False)
    op.create_index('code', 'vehicle_classes', ['code'], unique=True)
    op.drop_constraint(None, 'sign_in_history', type_='foreignkey')
    op.create_foreign_key('sign_in_history_ibfk_1', 'sign_in_history', 'admin_users', ['admin_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sign_in_history', 'user_agent',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('sign_in_history', 'result',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_service_zones_code'), table_name='service_zones')
    op.create_index('ix_service_zones_code', 'service_zones', ['code'], unique=False)
    op.create_index('code', 'service_zones', ['code'], unique=True)
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key('password_reset_tokens_ibfk_1', 'password_reset_tokens', 'admin_users', ['admin_user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_admin_user_id'), table_name='password_reset_tokens')
    op.create_index('token_hash', 'password_reset_tokens', ['token_hash'], unique=True)
    op.alter_column('password_reset_tokens', 'token_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_aircraft_types_code'), table_name='aircraft_types')
    op.create_index('ix_aircraft_types_code', 'aircraft_types', ['code'], unique=False)
    op.create_index('code', 'aircraft_types', ['code'], unique=True)
    op.drop_index(op.f('ix_air_routes_code'), table_name='air_routes')
    op.create_index('ix_air_routes_code', 'air_routes', ['code'], unique=False)
    op.create_index('code', 'air_routes', ['code'], unique=True)
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index('ix_admin_users_email', 'admin_users', ['email'], unique=False)
    op.create_index('email', 'admin_users', ['email'], unique=True)
    op.drop_constraint(None, 'admin_sessions', type_='foreignkey')
    op.create_foreign_key('admin_sessions_ibfk_1', 'admin_sessions', 'admin_users', ['admin_user_id'], ['id'], ondelete='CASCADE')
    op.create_index('refresh_token_hash', 'admin_sessions', ['refresh_token_hash'], unique=True)
    op.alter_column('admin_sessions', 'device_os',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('admin_sessions', 'refresh_token_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_admin_invite_tokens_token_hash'), table_name='admin_invite_tokens')
    op.create_index('ix_admin_invite_tokens_token_hash', 'admin_invite_tokens', ['token_hash'], unique=False)
    op.create_index('token_hash', 'admin_invite_tokens', ['token_hash'], unique=True)
    op.drop_index(op.f('ix_wallet_transactions_customer_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
