"""add_metrics_to_feature_flags

Revision ID: 9c8e0304238b
Revises: dd3bbfd12a26
Create Date: 2026-05-30 13:12:28.194567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8e0304238b'
down_revision: Union[str, None] = 'dd3bbfd12a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flags', sa.Column('metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_flags', 'metrics')
    # ### end Alembic commands ###
