"""add_booking_rules_to_platform_settings

Revision ID: a2838280369c
Revises: 92365e6f29ee
Create Date: 2026-05-30 17:34:38.503578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2838280369c'
down_revision: Union[str, None] = '92365e6f29ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('max_advance_days', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('min_advance_minutes', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('cancellation_free_window_min', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('cancellation_fee_pct', sa.Float(), nullable=True))
    op.add_column('platform_settings', sa.Column('max_cancellations_per_day', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('driver_acceptance_timeout_sec', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('max_dispatch_retries', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('auto_assign_enabled', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('free_waiting_minutes', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('waiting_charge_per_min', sa.Float(), nullable=True))
    op.add_column('platform_settings', sa.Column('max_active_bookings_per_rider', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'max_active_bookings_per_rider')
    op.drop_column('platform_settings', 'waiting_charge_per_min')
    op.drop_column('platform_settings', 'free_waiting_minutes')
    op.drop_column('platform_settings', 'auto_assign_enabled')
    op.drop_column('platform_settings', 'max_dispatch_retries')
    op.drop_column('platform_settings', 'driver_acceptance_timeout_sec')
    op.drop_column('platform_settings', 'max_cancellations_per_day')
    op.drop_column('platform_settings', 'cancellation_fee_pct')
    op.drop_column('platform_settings', 'cancellation_free_window_min')
    op.drop_column('platform_settings', 'min_advance_minutes')
    op.drop_column('platform_settings', 'max_advance_days')
    # ### end Alembic commands ###
