"""create_payments_tables

Revision ID: bb15508279ff
Revises: df6938de111d
Create Date: 2026-06-03 00:30:17.453105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb15508279ff'
down_revision: Union[str, None] = 'df6938de111d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('booking_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('booking_ref', sa.String(length=64), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('method', sa.Enum('upi', 'card', 'wallet', 'netbanking', 'corporate', 'cash', name='paymentmethod'), nullable=False),
    sa.Column('vpa', sa.String(length=255), nullable=True),
    sa.Column('gross_amount', sa.Integer(), nullable=False),
    sa.Column('gateway_fee', sa.Integer(), nullable=False),
    sa.Column('net_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('initiated', 'authorized', 'captured', 'refunded', 'part_refund', 'chargeback', 'invoiced', 'pending', 'failed', 'disputed', name='paymentstatus'), nullable=False),
    sa.Column('gateway_ref', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_batches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('gateway', sa.String(length=128), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_unmatched',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('count_label', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=False),
    sa.Column('tone', sa.String(length=16), nullable=False),
    sa.Column('cycle_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('refund_type', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunds')
    op.drop_table('reconciliation_unmatched')
    op.drop_table('reconciliation_batches')
    op.drop_table('payments')
    # ### end Alembic commands ###
