"""add_localization_to_platform_settings

Revision ID: bbd8d85c6dbd
Revises: 94fefaf90323
Create Date: 2026-05-30 22:11:35.393013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd8d85c6dbd'
down_revision: Union[str, None] = '94fefaf90323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('default_language', sa.String(length=10), nullable=True))
    op.add_column('platform_settings', sa.Column('supported_languages', sa.JSON(), nullable=True))
    op.add_column('platform_settings', sa.Column('rtl_enabled', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('date_format', sa.String(length=20), nullable=True))
    op.add_column('platform_settings', sa.Column('time_format', sa.String(length=5), nullable=True))
    op.add_column('platform_settings', sa.Column('week_starts_on', sa.String(length=10), nullable=True))
    op.add_column('platform_settings', sa.Column('currency_symbol_position', sa.String(length=10), nullable=True))
    op.add_column('platform_settings', sa.Column('decimal_separator', sa.String(length=1), nullable=True))
    op.add_column('platform_settings', sa.Column('thousands_separator', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'thousands_separator')
    op.drop_column('platform_settings', 'decimal_separator')
    op.drop_column('platform_settings', 'currency_symbol_position')
    op.drop_column('platform_settings', 'week_starts_on')
    op.drop_column('platform_settings', 'time_format')
    op.drop_column('platform_settings', 'date_format')
    op.drop_column('platform_settings', 'rtl_enabled')
    op.drop_column('platform_settings', 'supported_languages')
    op.drop_column('platform_settings', 'default_language')
    # ### end Alembic commands ###
