"""add_document_image_url

Revision ID: d47cf9e3acce
Revises: 3c3019762e67
Create Date: 2026-05-29 08:43:57.564932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47cf9e3acce'
down_revision: Union[str, None] = '3c3019762e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_documents', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_documents', 'image_url')
    # ### end Alembic commands ###
