"""add_module_14_promotions_referrals

Revision ID: daab56248ef4
Revises: 0fa38c92e3ff
Create Date: 2026-05-31 09:21:30.083387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daab56248ef4'
down_revision: Union[str, None] = '0fa38c92e3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('cap_minor', sa.Integer(), nullable=True),
    sa.Column('min_trip_value_minor', sa.Integer(), nullable=True),
    sa.Column('validity_from', sa.DateTime(), nullable=False),
    sa.Column('validity_to', sa.DateTime(), nullable=False),
    sa.Column('per_customer_limit', sa.Integer(), nullable=False),
    sa.Column('total_redemption_cap', sa.Integer(), nullable=True),
    sa.Column('total_budget_minor', sa.Integer(), nullable=False),
    sa.Column('budget_spent_minor', sa.Integer(), nullable=False),
    sa.Column('redemption_count', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('service_types', sa.JSON(), nullable=True),
    sa.Column('zones', sa.JSON(), nullable=True),
    sa.Column('new_customers_only', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_code'), 'promotions', ['code'], unique=True)
    op.create_table('referral_programs',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('referrer_reward_minor', sa.Integer(), nullable=False),
    sa.Column('referee_reward_minor', sa.Integer(), nullable=False),
    sa.Column('qualifying_event', sa.String(length=50), nullable=False),
    sa.Column('per_referrer_monthly_cap_minor', sa.Integer(), nullable=False),
    sa.Column('monthly_budget_minor', sa.Integer(), nullable=False),
    sa.Column('fraud_self_referral', sa.Boolean(), nullable=False),
    sa.Column('fraud_device_collusion', sa.Boolean(), nullable=False),
    sa.Column('fraud_velocity_limit', sa.Boolean(), nullable=False),
    sa.Column('fraud_payment_instrument', sa.Boolean(), nullable=False),
    sa.Column('fraud_manual_review_threshold_minor', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('referrer_id', sa.String(length=36), nullable=False),
    sa.Column('referee_id', sa.String(length=36), nullable=True),
    sa.Column('referral_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reward_minor', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referee_id'), 'referrals', ['referee_id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('coupon_redemptions',
    sa.Column('promotion_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_redemptions_customer_id'), 'coupon_redemptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_promotion_id'), 'coupon_redemptions', ['promotion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupon_redemptions_promotion_id'), table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_customer_id'), table_name='coupon_redemptions')
    op.drop_table('coupon_redemptions')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referee_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('referral_programs')
    op.drop_index(op.f('ix_promotions_code'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
