"""add_quiet_hours_to_platform_settings

Revision ID: db6e07eb52b7
Revises: f3e55df2c10e
Create Date: 2026-05-30 18:27:33.734801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6e07eb52b7'
down_revision: Union[str, None] = 'f3e55df2c10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=True))
    op.add_column('platform_settings', sa.Column('quiet_hours_start', sa.String(length=5), nullable=True))
    op.add_column('platform_settings', sa.Column('quiet_hours_end', sa.String(length=5), nullable=True))
    op.add_column('platform_settings', sa.Column('quiet_hours_action', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'quiet_hours_action')
    op.drop_column('platform_settings', 'quiet_hours_end')
    op.drop_column('platform_settings', 'quiet_hours_start')
    op.drop_column('platform_settings', 'quiet_hours_enabled')
    # ### end Alembic commands ###
