"""add_module_21_settings_tables

Revision ID: dd3bbfd12a26
Revises: 5d8d45a34601
Create Date: 2026-05-30 12:25:01.880223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3bbfd12a26'
down_revision: Union[str, None] = '5d8d45a34601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('rollout_pct', sa.Integer(), nullable=False),
    sa.Column('targeting', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('kill_switches',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tone', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('maintenance_windows',
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_entity', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('primary_region', sa.String(length=100), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=True),
    sa.Column('fiscal_year_start', sa.String(length=20), nullable=True),
    sa.Column('settlement_cycle', sa.String(length=20), nullable=True),
    sa.Column('driver_payout_day', sa.String(length=20), nullable=True),
    sa.Column('surge_ceiling', sa.Float(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.Column('last_edited_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_toggles',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('region_status',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_status')
    op.drop_table('platform_toggles')
    op.drop_table('platform_settings')
    op.drop_table('maintenance_windows')
    op.drop_table('kill_switches')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
