"""add_extended_booking_rules

Revision ID: f3e55df2c10e
Revises: a2838280369c
Create Date: 2026-05-30 18:06:18.184794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e55df2c10e'
down_revision: Union[str, None] = 'a2838280369c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('no_show_wait_minutes', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('no_show_fee_pct', sa.Float(), nullable=True))
    op.add_column('platform_settings', sa.Column('dispatch_initial_radius_m', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('dispatch_radius_step_m', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('dispatch_max_radius_m', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('rank_weight_distance', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('rank_weight_rating', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('rank_weight_acceptance', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('default_commission_pct', sa.Float(), nullable=True))
    op.add_column('platform_settings', sa.Column('refund_destination_default', sa.String(length=20), nullable=True))
    op.add_column('platform_settings', sa.Column('air_min_advance_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'air_min_advance_hours')
    op.drop_column('platform_settings', 'refund_destination_default')
    op.drop_column('platform_settings', 'default_commission_pct')
    op.drop_column('platform_settings', 'rank_weight_acceptance')
    op.drop_column('platform_settings', 'rank_weight_rating')
    op.drop_column('platform_settings', 'rank_weight_distance')
    op.drop_column('platform_settings', 'dispatch_max_radius_m')
    op.drop_column('platform_settings', 'dispatch_radius_step_m')
    op.drop_column('platform_settings', 'dispatch_initial_radius_m')
    op.drop_column('platform_settings', 'no_show_fee_pct')
    op.drop_column('platform_settings', 'no_show_wait_minutes')
    # ### end Alembic commands ###
